name: Build on pull requests

on:
  pull_request:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install pnpm
        run: npm install --global pnpm
      - name: pnpm install
        run: pnpm install
      - name: export
        run: npm run build
