name: Build Sapper and Deploy to remote server via FTP

on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Export Sapper
        uses: truewebartisans/actions-sapper@master
        with:
          args: --legacy --entry "/index.html /404.html"
      - name: Upload to FTP
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: __sapper__/export
          remoteDir: public_html
          forceSsl: true
